---
engines:
  duplication:
    exclude_paths:
      - "deepctr_torch/models/dcn.py"
      - "deepctr_torch/models/dcnmix.py"
      - "deepctr_torch/models/deepfm.py"
      - "deepctr_torch/models/difm.py"
      - "deepctr_torch/models/din.py"
      - "deepctr_torch/models/fibinet.py"
      - "deepctr_torch/models/ifm.py"
      - "deepctr_torch/models/nfm.py"
      - "deepctr_torch/models/onn.py"
      - "deepctr_torch/models/wdl.py"
      - "deepctr_torch/models/xdeepfm.py"
