from .wdl import WDL
from .deepfm import DeepFM
from .xdeepfm import xDeepFM
from .afm import AFM
from .autoint import AutoInt
from .dcn import DCN
from .fibinet import FiBiNET
from .pnn import PNN
from .nfm import NFM
from .mlr import MLR
